'use client'

import { FormEvent, useState } from 'react'
import { account } from '@/lib/appwrite'
import { ID } from 'appwrite'

export default function AuthPage(){
 const [mode,setMode]=useState<'login'|'signup'>('login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false)
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage('');try{if(mode==='signup'){await account.create(ID.unique(),email,password,name||undefined);await account.createEmailPasswordSession(email,password)}else{await account.createEmailPasswordSession(email,password)}window.location.href='/workspace'}catch(err){setMessage(err instanceof Error?err.message:'Authentication failed. Check your details and try again.')}finally{setBusy(false)}}
 return <main className="shell"><nav className="nav"><a className="brand" href="/" style={{textDecoration:'none',color:'inherit'}}><div className="mark">B</div>BRANCH</a></nav><section className="container" style={{minHeight:'calc(100vh - 72px)',display:'grid',placeItems:'center'}}><form onSubmit={submit} className="panel" style={{width:'min(430px,100%)',padding:25}}><div className="eyebrow">Private workspace</div><h1 style={{fontSize:34,letterSpacing:'-.04em',margin:'10px 0'}}>Your decisions, your model.</h1><p className="muted">Sign in to keep your decision work separate and private.</p>{mode==='signup'&&<div className="space"><label className="label">Name</label><input className="field" value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></div>}<div className="space"><label className="label">Email</label><input className="field" type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></div><div className="space"><label className="label">Password</label><input className="field" type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='signup'?'new-password':'current-password'}/></div>{message&&<p className="muted space" style={{color:'#ffabab'}}>{message}</p>}<button className="btn primary space" style={{width:'100%'}} disabled={busy}>{busy?'Working…':mode==='signup'?'Create account':'Sign in'}</button><button type="button" className="btn ghost space" style={{width:'100%'}} onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('')}}>{mode==='login'?'Create a new account':'I already have an account'}</button></form></section></main>
}
