'use client'

import { useMemo, useState } from 'react'
import type { Analysis } from '@/lib/engine'
import { recommendPath, simulateScenarios } from '@/lib/engine'

type Result=Analysis&{understanding?:string;assistantMessage?:string;clarifyingQuestions?:string[];intent?:string;confidenceLabel?:string}
const demo=`Should I launch my SaaS this month or spend two more weeks improving it? My goal is to maximize sustainable adoption without sacrificing product quality. I have a two-person team, a limited budget, and a school-year deadline. I prefer learning from real users, but I am uncertain whether the product is ready.`
const examples=[
 ['Startup','Should we launch now or keep improving for two weeks? Our goal is sustainable adoption. We have a two-person team, a limited budget, and a deadline this month. We prefer learning from real users but the product still needs polish.'],
 ['Career','Should I accept this opportunity now or wait for a better fit? My goal is long-term learning and a healthy schedule. I have another interview in two weeks, limited time to decide, and I prefer work that leaves room for study.'],
 ['Product','Should our team build feature A or feature B first? Our goal is to improve user retention. We have three developers, a six-week deadline, limited capacity, and early user feedback is stronger for feature A.']
]
function level(value:number,low:string,high:string){return value<=30?low:value>=70?high:'Moderate'}

export default function Home(){
 const[decision,setDecision]=useState('');const[analysis,setAnalysis]=useState<Result|null>(null);const[values,setValues]=useState<Record<string,number>>({});const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[tab,setTab]=useState<'paths'|'scenarios'|'why'>('paths');const[scenarioId,setScenarioId]=useState('current')
 const variables=useMemo(()=>analysis?.variables.map(v=>({...v,value:values[v.name]??v.value}))??[],[analysis,values])
 const liveRecommendation=useMemo(()=>analysis?recommendPath(analysis.options,analysis.goal,variables):{option:'',reason:''},[analysis,variables])
 const liveScenarios=useMemo(()=>analysis?simulateScenarios(variables):[],[analysis,variables])
 const selectedScenario=liveScenarios.find(s=>s.id===scenarioId)||liveScenarios.find(s=>s.id==='current')
 async function run(){setError('');if(!decision.trim()){setError('Write anything you want BRANCH to understand — a question, goal, topic, or decision.');return}setBusy(true);try{const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({decision})});const data=await r.json();if(!r.ok||!data.analysis)throw new Error(data.error||'Unable to process that message.');setAnalysis(data as Result);setValues(Object.fromEntries(data.analysis.variables.map((v:Analysis['variables'][number])=>[v.name,v.value])));setTab('paths');setScenarioId('current');window.setTimeout(()=>document.getElementById('workspace')?.scrollIntoView({behavior:'smooth',block:'start'}),40)}catch(e){setError(e instanceof Error?e.message:'Something went wrong. Try again.')}finally{setBusy(false)}}
 function loadDemo(){setDecision(demo);setAnalysis(null);setError('');window.setTimeout(()=>document.getElementById('workspace')?.scrollIntoView({behavior:'smooth'}),20)}
 function reset(){if(analysis)setValues(Object.fromEntries(analysis.variables.map(v=>[v.name,v.value])))}
 return <main className="shell">
  <nav className="nav"><a className="brand" href="#top"><span className="mark">B</span><span>BRANCH</span></a><div className="navRight"><span className="navlink">Decision intelligence</span><a href="#how">How it works</a><a href="#workspace">Workspace</a></div></nav>
  <section className="hero container" id="top"><div className="heroCopy"><div className="eyebrow">AI-powered decision simulation</div><h1>Explore the decision<br/><span>before you make it.</span></h1><p>BRANCH understands messy human input, answers what it can, separates real choices from context, and turns meaningful decisions into interactive simulations.</p><div className="actions"><button className="btn primary" onClick={()=>document.getElementById('workspace')?.scrollIntoView({behavior:'smooth'})}>Explore a decision <span>→</span></button><button className="btn ghost" onClick={loadDemo}>See a live example</button></div><div className="trustRow"><span>● Natural language</span><span>● Deterministic simulation</span><span>● Explainable reasoning</span></div></div><div className="heroCard"><div className="cardTop"><div><div className="miniLabel">Simulation preview</div><strong>One choice. Multiple ways it can unfold.</strong></div><span className="liveDot">● READY</span></div><div className="branchPreview"><div className="previewDecision"><span>YOUR DECISION</span><b>Launch now or improve?</b></div><div className="previewLine"/><div className="previewBranches"><div><span>PATH A</span><b>Launch now</b><small>Learn sooner · accept uncertainty</small></div><div><span>PATH B</span><b>Improve first</b><small>More readiness · delay learning</small></div></div><div className="previewLine short"/><div className="previewOutcome"><span>CHANGE A CONDITION</span><b>What if the deadline tightens?</b></div></div><div className="previewBottom"><span>Paths <b>2+</b></span><span>Drivers <b>6</b></span><span>Scenarios <b>3</b></span></div></div></section>
  <section className="problemBand"><div className="container split"><div><div className="eyebrow">The principle</div><h2>Talk to it like a human. Explore it like a model.</h2></div><p>BRANCH does not require magic trigger words. A question, fragment, goal, comparison, or messy thought gets interpreted first. When it becomes a real decision, the system extracts paths and meaningful conditions, then uses deterministic code to explore what could happen.</p></div></section>
  <section className="section container" id="how"><div className="sectionHeading"><div><div className="eyebrow">How BRANCH works</div><h2>From human language to an explorable decision.</h2></div><p>AI handles understanding and explanation. BRANCH validates the structure and runs the simulation. That separation keeps the model inspectable instead of making the LLM the entire product.</p></div><div className="steps">{[['01','Understand','Read questions, slang, fragments, goals, constraints, preferences, timing and uncertainty.'],['02','Structure','Separate actual choices from facts, priorities, assumptions and missing context.'],['03','Simulate','Change meaningful conditions and trace how the trade-offs could move.'],['04','Explain','Answer naturally, recommend conditionally, and show what would change the result.']].map(([n,t,d])=><article className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="workspaceSection" id="workspace"><div className="container"><div className="sectionHeading"><div><div className="eyebrow">Decision workspace</div><h2>Say what is on your mind. BRANCH will figure out what kind of help you need.</h2></div><p>It can answer a normal question, recognize a goal, acknowledge a topic, or build a decision model when the information supports one. No fake variables. No arbitrary winner score.</p></div><div className="workspace">
   <aside className="inputPanel panel"><div className="panelLabel"><span>01</span> Your message</div><textarea className="field textarea" value={decision} onChange={e=>setDecision(e.target.value)} placeholder="Ask a question, describe a decision, tell BRANCH a goal, or just start with what is on your mind…"/><div className="contextChecklist"><span>BRANCH can understand</span><b>Questions and comparisons</b><b>Goals and plans</b><b>Messy natural language</b><b>Constraints, preferences and unknowns</b></div><button className="btn primary full" onClick={run} disabled={busy}>{busy?<><span className="spinner"/> Thinking…</>:<>Ask BRANCH <span>→</span></>}</button>{error&&<div className="errorBox" role="alert">{error}</div>}<div className="examples"><div className="miniLabel">Try a full decision</div>{examples.map(([label,text])=><button key={label} onClick={()=>setDecision(text)}><span>{label}</span>{text}</button>)}</div></aside>
   <section className="modelPanel panel">{!analysis?<div className="emptyState"><div className="emptyIcon">⌁</div><div className="eyebrow">No conversation yet</div><h3>Start anywhere.</h3><p>Ask BRANCH a normal question, give it a goal, mention a topic, or describe a difficult choice. It will respond to what you actually said before asking for anything else.</p><button className="btn ghost" onClick={loadDemo}>Load a complete example</button></div>:<>
    <div className="modelHeader"><div><div className="miniLabel">BRANCH understood</div><h3>{analysis.title}</h3><p>{analysis.understanding||analysis.summary}</p></div><div className="confidence"><b>{analysis.confidenceLabel|| (analysis.contextQuality==='ready'?'Model ready':'More context needed')}</b><span>status</span></div></div>
    <div className="resultCard" style={{marginTop:18}}><div className="aiBadge">✦ BRANCH'S RESPONSE</div><p className="goalText" style={{fontSize:14,color:'#c9d2dc',marginTop:10}}>{analysis.assistantMessage||analysis.summary}</p>{analysis.intent&&<div className="pill" style={{display:'inline-block'}}>{analysis.intent.replace(/_/g,' ')}</div>}</div>
    {analysis.contextQuality==='needs-context'&&<div className="contextWarning"><div className="warningIcon">?</div><div><strong>Here is what BRANCH still needs — and why.</strong><span>{analysis.options.length>=2?'The paths are clear, but the priority or constraint that determines the trade-off is not fully known yet.':'This is not a complete decision model yet, so BRANCH will not invent choices or consequences.'}</span>{(analysis.clarifyingQuestions?.length?analysis.clarifyingQuestions:analysis.missingContext).length>0&&<ul>{(analysis.clarifyingQuestions?.length?analysis.clarifyingQuestions:analysis.missingContext).map(q=><li key={q}>{q}</li>)}</ul>}<div className="contextPrompt"><b>What happens next:</b> Add the missing detail in your own words. BRANCH will re-read the whole situation, not just the new sentence.</div></div></div>}
    {analysis.contextQuality==='ready'&&<><div className="tabs" role="tablist"><button className={tab==='paths'?'active':''} onClick={()=>setTab('paths')}>Paths</button><button className={tab==='scenarios'?'active':''} onClick={()=>setTab('scenarios')}>What could happen</button><button className={tab==='why'?'active':''} onClick={()=>setTab('why')}>Why this recommendation</button></div>
     {tab==='paths'&&<div className="modelGrid"><div className="resultCard pathCard"><div className="cardHeading"><span>Your possible paths</span><span className="pill">{analysis.options.length} choices</span></div><p className="cardIntro">These are the actual choices BRANCH found. The descriptions explain the kind of trade-off each path creates; there is no fake score.</p><div className="pathList">{analysis.options.map((option,index)=><article className={`pathItem ${option===liveRecommendation.option?'recommendedPath':''}`} key={option}><div className="pathNumber">0{index+1}</div><div className="pathBody"><div className="pathMeta"><span>PATH {index+1}</span>{option===liveRecommendation.option&&<em>BEST FIT FOR YOUR CURRENT CONTEXT</em>}</div><b>{option}</b><p>{/(wait|delay|improve|research|learn|prepare|test)/i.test(option)?'Creates more room to learn, prepare, validate, or reduce uncertainty before a larger commitment.':/(launch|start|act|accept|commit|ship|now)/i.test(option)?'Creates momentum sooner, while accepting more of the uncertainty that exists today.':'Creates a distinct commitment with its own benefits, costs, dependencies, and uncertainty.'}</p></div></article>)}</div></div><div className="resultCard recommendationCard"><div className="aiBadge">✦ CONTEXTUAL RECOMMENDATION</div><h3>{liveRecommendation.option}</h3><p>{liveRecommendation.reason}</p><div className="recommendationRule"><span>WHAT WOULD CHANGE IT</span><b>{analysis.nextStep}</b></div></div><div className="resultCard fullCard"><div className="cardHeading"><span>Change the conditions</span><span className="muted">Live model</span></div><p className="cardIntro">These drivers came from the situation you described. Move one and the recommendation and scenarios recalculate immediately.</p>{variables.map(v=><label className="variable" key={v.name}><div className="variableTop"><div><b>{v.name}</b><span>{v.description}</span></div><output>{level(v.value,v.lowLabel,v.highLabel)}</output></div><input type="range" min="0" max="100" value={v.value} onChange={e=>setValues(p=>({...p,[v.name]:Number(e.target.value)}))}/><div className="rangeLabels"><span>{v.lowLabel}</span><span>{v.highLabel}</span></div></label>)}<div className="variableFooter"><button className="btn ghost small" onClick={reset}>Reset conditions</button><span>Changing a condition changes the model, not reality.</span></div></div></div>}
     {tab==='scenarios'&&<div className="scenarioView"><div className="scenarioIntro"><div className="miniLabel">Generated from the current model</div><h3>What could happen?</h3><p>These are plausible consequence patterns, not guaranteed forecasts. Change a driver in Paths and come back here to compare.</p></div><div className="scenarioCards">{liveScenarios.map(s=><button className={`scenarioCard ${scenarioId===s.id?'selected':''}`} key={s.id} onClick={()=>setScenarioId(s.id)}><span>{s.id==='current'?'BASELINE':'SCENARIO'}</span><b>{s.name}</b><p>{s.description}</p><small>{s.changes.slice(0,3).map(c=>`${c.variable}: ${c.label}`).join(' · ')}</small></button>)}</div>{selectedScenario&&<div className="scenarioResult resultCard"><div className="cardHeading"><span>{selectedScenario.name}</span><span className="pill">LIVE EXPLORATION</span></div><p className="scenarioDescription">{selectedScenario.description}</p><div className="scenarioColumns"><div><h4>Conditions</h4>{selectedScenario.changes.map(c=><div className="changeRow" key={c.variable}><span>{c.variable}</span><b>{c.label}</b></div>)}</div><div><h4>What could happen</h4>{selectedScenario.effects.map(x=><p className="bullet" key={x}>→ {x}</p>)}<h4 className="subhead">Trade-offs to watch</h4>{selectedScenario.tradeoffs.map(x=><p className="bullet mutedBullet" key={x}>↳ {x}</p>)}</div></div></div>}</div>}
     {tab==='why'&&<div className="explainGrid"><div className="explainMain resultCard"><div className="aiBadge">✦ WHY THIS PATH</div><h3>{liveRecommendation.option} fits the situation you gave BRANCH</h3><p>{liveRecommendation.reason}</p>{variables.slice(0,5).map((v,i)=><div className="insight" key={v.name}><span>0{i+1}</span><div><b>{v.name}</b><p>{v.description} It is currently <strong>{level(v.value,v.lowLabel,v.highLabel)}</strong>. A meaningful change here can change the recommendation.</p></div></div>)}<div className="insight"><span>!</span><div><b>Conditional, not certain</b><p>BRANCH does not know future events. Its recommendation is based on the context and priorities supplied.</p></div></div></div><div className="explainSide resultCard"><div className="cardHeading"><span>Risks</span><span className="pill danger">WATCH</span></div>{analysis.risks.map((x,i)=><p className="risk" key={x}><span>0{i+1}</span>{x}</p>)}<div className="cardHeading second"><span>Assumptions</span></div>{analysis.assumptions.map(x=><p className="assumption" key={x}>✓ {x}</p>)}</div></div>}
    </>}
   </>}</section>
  </div></div></section>
  <section className="section container useCases"><div className="eyebrow">One engine. Many decisions.</div><h2>Useful anywhere uncertainty matters.</h2><div className="useGrid">{['Launching a product','Career & education choices','Travel & major plans','Small-business planning','Team prioritization','Everyday complex choices'].map((x,i)=><div className="useCard" key={x}><span>0{i+1}</span><b>{x}</b><p>Explore choices, constraints, conditions, consequences, and trade-offs.</p></div>)}</div></section>
  <section className="finalCta"><div className="container"><div className="eyebrow">Your context. Your priorities. Your exploration.</div><h2>Don't just ask AI what to do.<br/><span>Explore what could happen.</span></h2><p>BRANCH answers naturally first, then gives you an explorable model when a real decision emerges.</p><button className="btn primary" onClick={()=>document.getElementById('workspace')?.scrollIntoView({behavior:'smooth'})}>Build a decision <span>→</span></button></div></section>
  <footer className="footer"><div>BRANCH</div><span>Explore the decision before you make it.</span><b>Built By Koglesh R. Murugan</b></footer>
 </main>
}
