'use client'

import { useMemo, useState } from 'react'
import type { Analysis } from '@/lib/engine'
import { recommendPath, simulateScenarios } from '@/lib/engine'

const demo = `Should I launch my SaaS this month or spend two more weeks improving it? My goal is to maximize sustainable adoption without sacrificing product quality. I have a two-person team, a limited budget, and a school-year deadline. I prefer learning from real users, but I am uncertain whether the product is ready.`
const examples = [
  ['Startup', 'Should we launch now or keep improving for two weeks? Our goal is sustainable adoption. We have a two-person team, a limited budget, and a deadline this month. We prefer learning from real users but the product still needs polish.'],
  ['Career', 'Should I accept this opportunity now or wait for a better fit? My goal is long-term learning and a healthy schedule. I have another interview in two weeks, limited time to decide, and I prefer work that leaves room for study.'],
  ['Product', 'Should our team build feature A or feature B first? Our goal is to improve user retention. We have three developers, a six-week deadline, limited capacity, and early user feedback is stronger for feature A.'],
]

function level(value: number, low: string, high: string) { return value <= 30 ? low : value >= 70 ? high : 'Moderate' }

export default function Home() {
  const [decision, setDecision] = useState('')
  const [analysis, setAnalysis] = useState<Analysis | null>(null)
  const [values, setValues] = useState<Record<string, number>>({})
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const [tab, setTab] = useState<'paths' | 'scenarios' | 'why'>('paths')
  const [scenarioId, setScenarioId] = useState('current')

  const variables = useMemo(() => analysis?.variables.map(v => ({ ...v, value: values[v.name] ?? v.value })) ?? [], [analysis, values])
  const liveRecommendation = useMemo(() => analysis ? recommendPath(analysis.options, analysis.goal, variables) : { option: '', reason: '' }, [analysis, variables])
  const liveScenarios = useMemo(() => analysis ? simulateScenarios(variables) : [], [analysis, variables])
  const selectedScenario = liveScenarios.find(s => s.id === scenarioId) ?? liveScenarios.find(s => s.id === 'current')

  async function run() {
    setError('')
    if (decision.trim().length < 20) { setError('Give BRANCH a little more context: the choices, your goal, and at least one constraint, preference, or uncertainty.'); return }
    setBusy(true)
    try {
      const response = await fetch('/api/analyze', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ decision }) })
      const data = await response.json()
      if (!response.ok || !data.analysis) throw new Error(data.error || 'Unable to build the decision model.')
      setAnalysis(data.analysis)
      setValues(Object.fromEntries(data.analysis.variables.map((v: Analysis['variables'][number]) => [v.name, v.value])))
      setTab('paths'); setScenarioId('current')
      window.setTimeout(() => document.getElementById('workspace')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 40)
    } catch (err) { setError(err instanceof Error ? err.message : 'Something went wrong. Try again.') }
    finally { setBusy(false) }
  }

  function loadDemo() { setDecision(demo); setAnalysis(null); setError(''); window.setTimeout(() => document.getElementById('workspace')?.scrollIntoView({ behavior: 'smooth' }), 20) }
  function reset() { if (analysis) setValues(Object.fromEntries(analysis.variables.map(v => [v.name, v.value]))) }

  return <main className="shell">
    <nav className="nav"><a className="brand" href="#top" aria-label="BRANCH home"><span className="mark">B</span><span>BRANCH</span></a><div className="navRight"><span className="navlink">Decision intelligence</span><a href="#how">How it works</a><a href="#workspace">Workspace</a></div></nav>

    <section className="hero container" id="top"><div className="heroCopy"><div className="eyebrow">AI-powered decision simulation</div><h1>Explore the decision<br /><span>before you make it.</span></h1><p>BRANCH turns a complicated choice into a living model of paths, conditions, consequences, and trade-offs. It can recommend a path when your context supports one — while showing what could make that recommendation change.</p><div className="actions"><button className="btn primary" onClick={() => document.getElementById('workspace')?.scrollIntoView({ behavior: 'smooth' })}>Explore a decision <span>→</span></button><button className="btn ghost" onClick={loadDemo}>See a live example</button></div><div className="trustRow"><span>● Context-aware</span><span>● No credit system</span><span>● Explainable simulation</span></div></div>
      <div className="heroCard"><div className="cardTop"><div><div className="miniLabel">Simulation preview</div><strong>One choice. Multiple ways it can unfold.</strong></div><span className="liveDot">● READY</span></div><div className="branchPreview"><div className="previewDecision"><span>YOUR DECISION</span><b>Launch now or improve?</b></div><div className="previewLine" /><div className="previewBranches"><div><span>PATH A</span><b>Launch now</b><small>Learn sooner · accept uncertainty</small></div><div><span>PATH B</span><b>Improve first</b><small>More readiness · delay learning</small></div></div><div className="previewLine short" /><div className="previewOutcome"><span>CHANGE A CONDITION</span><b>What if the deadline tightens?</b></div></div><div className="previewBottom"><span>Paths <b>2</b></span><span>Drivers <b>5</b></span><span>Scenarios <b>3</b></span></div></div></section>

    <section className="problemBand"><div className="container split"><div><div className="eyebrow">The principle</div><h2>A decision tool should explain its reasoning, not hide it behind a number.</h2></div><p>BRANCH separates language understanding from deterministic simulation. Your goal, preferences, constraints, timing, and uncertainty shape the model. If your input is too vague, it tells you precisely what to add instead of fabricating certainty.</p></div></section>

    <section className="section container" id="how"><div className="sectionHeading"><div><div className="eyebrow">How BRANCH works</div><h2>From messy thought to an explorable decision model.</h2></div><p>It identifies actual choices first, then finds the conditions that can change the trade-off. The recommendation is conditional on what you told BRANCH.</p></div><div className="steps">{[['01','Understand','Read the decision, goal, preferences, constraints, timing, and uncertainty.'],['02','Structure','Separate real choices from the context that influences them.'],['03','Simulate','Generate context-specific conditions and trace their consequences.'],['04','Explain','Recommend when justified, show why, and reveal what would change it.']].map(([n,t,d]) => <article className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>

    <section className="workspaceSection" id="workspace"><div className="container"><div className="sectionHeading"><div><div className="eyebrow">Decision workspace</div><h2>Give BRANCH the situation. Then explore what follows.</h2></div><p>Write naturally. BRANCH will use your choices, goals, preferences, limits, and unknowns. If something important is missing, it will ask for that specific piece instead of making it up.</p></div><div className="workspace">
      <aside className="inputPanel panel"><div className="panelLabel"><span>01</span> Your situation</div><textarea className="field textarea" value={decision} onChange={e => setDecision(e.target.value)} placeholder="Tell BRANCH what you're deciding, what you want, what you can work with, and what you're unsure about…" /><div className="contextChecklist"><span>BRANCH looks for</span><b>Choices you can actually make</b><b>Your goal + preferences</b><b>Time, budget, people, or other limits</b><b>Unknowns that could change the outcome</b></div><button className="btn primary full" onClick={run} disabled={busy}>{busy ? <><span className="spinner" /> Understanding your decision…</> : <>Build my decision model <span>→</span></>}</button>{error && <div className="errorBox" role="alert">{error}</div>}<div className="examples"><div className="miniLabel">Start with a complete situation</div>{examples.map(([label,text]) => <button key={label} onClick={() => setDecision(text)}><span>{label}</span>{text}</button>)}</div></aside>

      <section className="modelPanel panel">{!analysis ? <div className="emptyState"><div className="emptyIcon">⌁</div><div className="eyebrow">No model yet</div><h3>Start with the decision behind the question.</h3><p>“I want to move abroad” is an outcome, not a decision. Tell BRANCH the choices you are considering, your priorities, and the constraints around them. It can then build something you can actually interrogate.</p><button className="btn ghost" onClick={loadDemo}>Load the live example</button></div> : <>
        <div className="modelHeader"><div><div className="miniLabel">BRANCH understood</div><h3>{analysis.title}</h3><p>{analysis.summary}</p></div><div className="contextBadge"><b>{analysis.contextConfidence}%</b><span>context fit</span></div></div>
        {analysis.contextQuality === 'needs-context' && <div className="contextWarning"><div className="warningIcon">!</div><div><strong>BRANCH needs a little more context before it branches.</strong><span>It understands the intent, but it will not invent choices or consequences you did not provide.</span><ul>{analysis.missingContext.map(item => <li key={item}>{item}</li>)}</ul><div className="contextPrompt"><b>Be specific:</b> “I’m deciding between A and B. My goal is __. I prefer __. I can __. I cannot __. The biggest unknown is __.”</div></div></div>}
        {analysis.contextQuality === 'ready' && <><div className="tabs" role="tablist"><button className={tab === 'paths' ? 'active' : ''} onClick={() => setTab('paths')}>Paths</button><button className={tab === 'scenarios' ? 'active' : ''} onClick={() => setTab('scenarios')}>What could happen</button><button className={tab === 'why' ? 'active' : ''} onClick={() => setTab('why')}>Why this recommendation</button></div>

        {tab === 'paths' && <div className="modelGrid"><div className="resultCard pathCard"><div className="cardHeading"><span>Your possible paths</span><span className="pill">{analysis.options.length} choices</span></div><p className="cardIntro">These are the choices BRANCH found in your description. No fake winner score — just the paths and their consequences.</p><div className="pathList">{analysis.options.map((option,index) => <article className={`pathItem ${option === liveRecommendation.option ? 'recommendedPath' : ''}`} key={option}><div className="pathNumber">0{index + 1}</div><div className="pathBody"><div className="pathMeta"><span>PATH {index + 1}</span>{option === liveRecommendation.option && <em>BEST FIT FOR YOUR CURRENT PRIORITY</em>}</div><b>{option}</b><p>{/(wait|delay|improve|research|learn|prepare)/i.test(option) ? 'This path gives you more room to learn, prepare, or reduce uncertainty before committing.' : /(launch|start|act|accept|commit|ship|now)/i.test(option) ? 'This path creates momentum sooner, while accepting more of the uncertainty that exists today.' : 'This path creates a distinct commitment with its own balance of flexibility, effort, and uncertainty.'}</p></div></article>)}</div></div>
          <div className="resultCard recommendationCard"><div className="aiBadge">✦ CONTEXTUAL RECOMMENDATION</div><h3>{liveRecommendation.option}</h3><p>{liveRecommendation.reason}</p><div className="recommendationRule"><span>WHAT WOULD CHANGE IT</span><b>{analysis.nextStep}</b></div></div>
          <div className="resultCard fullCard"><div className="cardHeading"><span>Adjust the conditions</span><span className="muted">Built from your context</span></div><p className="cardIntro">These are real decision drivers, not arbitrary scores. Move one and BRANCH immediately re-evaluates the recommendation and the generated scenarios.</p>{variables.map(variable => <label className="variable" key={variable.name}><div className="variableTop"><div><b>{variable.name}</b><span>{variable.description}</span></div><output>{level(variable.value, variable.lowLabel, variable.highLabel)}</output></div><input type="range" min="0" max="100" value={variable.value} onChange={e => setValues(previous => ({ ...previous, [variable.name]: Number(e.target.value) }))} aria-label={`${variable.name} condition`} /><div className="rangeLabels"><span>{variable.lowLabel}</span><span>{variable.highLabel}</span></div></label>)}<div className="variableFooter"><button className="btn ghost small" onClick={reset}>Reset conditions</button><span>Changing a condition changes the model, not reality.</span></div></div></div>}

        {tab === 'scenarios' && <div className="scenarioView"><div className="scenarioIntro"><div><div className="miniLabel">Generated from your current conditions</div><h3>What could happen next?</h3><p>These scenarios update when you adjust a driver. They describe plausible consequences, not guaranteed forecasts.</p></div></div><div className="scenarioCards">{liveScenarios.map(scenario => <button className={`scenarioCard ${scenarioId === scenario.id ? 'selected' : ''}`} key={scenario.id} onClick={() => setScenarioId(scenario.id)}><span>{scenario.id === 'current' ? 'BASELINE' : 'SCENARIO'}</span><b>{scenario.name}</b><p>{scenario.description}</p><small>{scenario.changes.slice(0,3).map(change => `${change.variable}: ${change.label}`).join(' · ')}</small></button>)}</div>{selectedScenario && <div className="scenarioResult resultCard"><div className="cardHeading"><span>{selectedScenario.name}</span><span className="pill">LIVE EXPLORATION</span></div><p className="scenarioDescription">{selectedScenario.description}</p><div className="scenarioColumns"><div><h4>Conditions</h4>{selectedScenario.changes.map(change => <div className="changeRow" key={change.variable}><span>{change.variable}</span><b>{change.label}</b></div>)}</div><div><h4>What could happen</h4>{selectedScenario.effects.map(effect => <p className="bullet" key={effect}>→ {effect}</p>)}<h4 className="subhead">Trade-offs to watch</h4>{selectedScenario.tradeoffs.map(tradeoff => <p className="bullet mutedBullet" key={tradeoff}>↳ {tradeoff}</p>)}</div></div></div>}</div>}

        {tab === 'why' && <div className="explainGrid"><div className="explainMain resultCard"><div className="aiBadge">✦ WHY THIS PATH</div><h3>{liveRecommendation.option} fits the situation you gave BRANCH</h3><p>{liveRecommendation.reason}</p>{variables.slice(0,5).map((variable,index) => <div className="insight" key={variable.name}><span>0{index + 1}</span><div><b>{variable.name}</b><p>{variable.description} It is currently <strong>{level(variable.value, variable.lowLabel, variable.highLabel)}</strong>. A meaningful change here can change the recommendation.</p></div></div>)}<div className="insight"><span>!</span><div><b>Conditional, not certain</b><p>BRANCH cannot know future events or private information. Its recommendation is based on the situation and priorities you supplied.</p></div></div></div><div className="explainSide resultCard"><div className="cardHeading"><span>Risks</span><span className="pill danger">WATCH</span></div>{analysis.risks.map((risk,index) => <p className="risk" key={risk}><span>0{index + 1}</span>{risk}</p>)}<div className="cardHeading second"><span>Assumptions</span></div>{analysis.assumptions.map(assumption => <p className="assumption" key={assumption}>✓ {assumption}</p>)}</div></div>}
        </>}
      </>}</section>
    </div></div></section>

    <section className="section container useCases"><div className="eyebrow">One engine. Many decisions.</div><h2>Useful anywhere uncertainty matters.</h2><div className="useGrid">{['Launching a product','Career & education choices','Travel & major plans','Small-business planning','Team prioritization','Everyday complex choices'].map((item,index) => <div className="useCard" key={item}><span>0{index + 1}</span><b>{item}</b><p>Explore choices, constraints, conditions, consequences, and trade-offs.</p></div>)}</div></section>
    <section className="finalCta"><div className="container"><div className="eyebrow">Your context. Your priorities. Your exploration.</div><h2>Don't just ask AI what to do.<br /><span>Explore what could happen.</span></h2><p>BRANCH helps you see the decision from more than one angle — and understand what would change your mind.</p><button className="btn primary" onClick={() => document.getElementById('workspace')?.scrollIntoView({ behavior: 'smooth' })}>Build a decision <span>→</span></button></div></section>
    <footer className="footer"><div>BRANCH</div><span>Explore the decision before you make it.</span><b>Built By Koglesh R. Murugan</b></footer>
  </main>
}
